name: ZenML CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialize ZenML
      run: |
        zenml init
        zenml orchestrator register local_orchestrator --flavor=local
        zenml metadata-store register local_metadata_store --flavor=sqlite --database=metadata.db
        zenml artifact-store register local_artifact_store --flavor=local --path=./artifacts
        zenml stack register local_stack -m local_metadata_store -a local_artifact_store -o local_orchestrator
        zenml stack set local_stack

    - name: Run ZenML pipeline
      run: |
        python run_pipeline.py
